"""Report builder for phase B — LLM synthesis with stub fallback."""

from __future__ import annotations

from geegoo_agent.memory.models import BotStock, PreMarketWorking
from geegoo_agent.runtime.llm_tasks import PreMarketSynthesis
from geegoo_agent.tools.mappings import attitude_to_result, is_a_share


def build_stub_report_content(working: PreMarketWorking, code: str) -> str:
    ws = working.stocks[code]
    bot = _bot_for_code(working, code)
    mc = working.market_context

    # 构建指数概况
    index_lines = ["## 一、市场概况", ""]
    index_map = {
        "^DJI.US": "道琼斯工业指数",
        "^IXIC.US": "纳斯达克综合指数",
        "000001.SH": "上证指数",
        "399001.SZ": "深证成指",
        "800000.HK": "恒生指数",
    }
    for idx_code, label in index_map.items():
        analysis = mc.index_analysis_refs.get(idx_code, "")
        if analysis:
            index_lines.append(f"### {label}\n{analysis[:200]}\n")
        else:
            index_lines.append(f"### {label}\n暂无数据\n")

    # 构建新闻摘要
    news_lines = ["## 二、市场新闻摘要", ""]
    for mk, news_raw in mc.market_news.items():
        mk_label = {"US": "美股", "CN": "A股", "HK": "港股"}.get(mk, mk)
        news_lines.append(f"### {mk_label}新闻\n{news_raw[:300]}\n")

    # 资金流向与分布（A 股跳过）
    section = 3
    if not is_a_share(code):
        cap_lines = [f"## {section}、资金流向与分布", ""]
        cap_lines.append(f"### 资金流向\n{ws.capital_flow_summary or '暂无数据'}")
        cap_lines.append(f"\n### 资金分布\n{ws.capital_distribution_summary or '暂无数据'}")
        section += 1
    else:
        cap_lines = []

    # 周线技术分析
    weekly_lines = [f"## {section}、周线技术分析", "", ws.weekly_analysis_ref or "暂无数据"]
    section += 1

    # Bot 态度
    attitude_lines = [f"## {section}、Bot 盘前态度", "", f"态度：{ws.attitude or 'neutral'}"]
    section += 1

    # 综合判断
    summary_lines = [
        f"## {section}、综合判断",
        "",
        "LLM 合成未执行，以下为 stub 模式默认值。",
        "- result: neutral",
        "- confidence: low",
        "- suggestion: hold",
        "- reason: phase B stub fallback，LLM 合成未运行，请检查日志。",
    ]
    section += 1

    # 个股新闻
    stock_news_lines = [
        f"## {section}、个股新闻",
        "",
        ws.stock_news_summary or "暂无数据",
    ]

    lines = [
        f"# 盘前报告 — {bot.stock_name} ({code})",
        "",
    ]
    lines.extend(index_lines)
    lines.extend(news_lines)
    if cap_lines:
        lines.extend(cap_lines)
    lines.extend(weekly_lines)
    lines.extend(attitude_lines)
    lines.extend(summary_lines)
    lines.extend(stock_news_lines)
    lines.append("")
    lines.append("_Generated by geegoo-agent phase B stub (Step 11)_")
    return "\n".join(lines)


def build_report_content(working: PreMarketWorking, code: str) -> str:
    ws = working.stocks[code]
    if ws.synthesis:
        synthesis = PreMarketSynthesis.model_validate(ws.synthesis)
        return synthesis.report
    return build_stub_report_content(working, code)


def build_create_report_args(working: PreMarketWorking, code: str) -> dict:
    bot = _bot_for_code(working, code)
    ws = working.stocks[code]
    if ws.synthesis:
        synthesis = PreMarketSynthesis.model_validate(ws.synthesis)
        return {
            "code": bot.code,
            "stock_name": bot.stock_name,
            "bot_id": bot.bot_id,
            "bot_name": bot.bot_name,
            "bot_type": bot.bot_type,
            **synthesis.model_dump(),
        }

    attitude = ws.attitude or "neutral"
    result = attitude_to_result(attitude)
    report = build_stub_report_content(working, code)
    return {
        "code": bot.code,
        "stock_name": bot.stock_name,
        "bot_id": bot.bot_id,
        "bot_name": bot.bot_name,
        "bot_type": bot.bot_type,
        "result": result,
        "confidence": "medium",
        "reason": f"Phase B stub based on attitude={attitude}",
        "suggestion": "hold",
        "report": report,
        "summary": report[:200],
    }


def _bot_for_code(working: PreMarketWorking, code: str) -> BotStock:
    for bot in working.bot_codes:
        if bot.code == code:
            return bot
    raise ValueError(f"bot not found for code: {code}")
