"""Report builder for phase B — LLM synthesis with stub fallback."""

from __future__ import annotations

from geegoo_agent.memory.models import BotStock, PreMarketWorking
from geegoo_agent.runtime.llm_tasks import PreMarketSynthesis
from geegoo_agent.tools.mappings import attitude_to_result


def build_stub_report_content(working: PreMarketWorking, code: str) -> str:
    ws = working.stocks[code]
    bot = _bot_for_code(working, code)
    lines = [
        f"# 盘前报告 — {bot.stock_name} ({code})",
        "",
        "## 周线技术分析",
        ws.weekly_analysis_ref or "暂无",
        "",
        "## 昨日 Bot 态度",
        ws.attitude or "neutral",
        "",
        "## 资金流向",
        ws.capital_flow_summary or "暂无",
        "",
        "## 资金分布",
        ws.capital_distribution_summary or "暂无",
        "",
        "_Generated by geegoo-agent phase B stub (Step 11)_",
    ]
    return "\n".join(lines)


def build_report_content(working: PreMarketWorking, code: str) -> str:
    ws = working.stocks[code]
    if ws.synthesis:
        synthesis = PreMarketSynthesis.model_validate(ws.synthesis)
        return synthesis.report
    return build_stub_report_content(working, code)


def build_create_report_args(working: PreMarketWorking, code: str) -> dict:
    bot = _bot_for_code(working, code)
    ws = working.stocks[code]
    if ws.synthesis:
        synthesis = PreMarketSynthesis.model_validate(ws.synthesis)
        return {
            "code": bot.code,
            "stock_name": bot.stock_name,
            "bot_id": bot.bot_id,
            "bot_name": bot.bot_name,
            "bot_type": bot.bot_type,
            **synthesis.model_dump(),
        }

    attitude = ws.attitude or "neutral"
    result = attitude_to_result(attitude)
    report = build_stub_report_content(working, code)
    return {
        "code": bot.code,
        "stock_name": bot.stock_name,
        "bot_id": bot.bot_id,
        "bot_name": bot.bot_name,
        "bot_type": bot.bot_type,
        "result": result,
        "confidence": "medium",
        "reason": f"Phase B stub based on attitude={attitude}",
        "suggestion": "hold",
        "report": report,
        "summary": report[:200],
    }


def _bot_for_code(working: PreMarketWorking, code: str) -> BotStock:
    for bot in working.bot_codes:
        if bot.code == code:
            return bot
    raise ValueError(f"bot not found for code: {code}")
